version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ebac_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vendas_online
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: S3nh@F0rt3!2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
